# configuration for https://travis-ci.org/bitcoinj/bitcoinj
sudo: true
dist: trusty
language: java
jdk: openjdk8
install: true # remove default
before_install:
  - wget https://oss.sonatype.org/content/repositories/releases/org/javafxports/dalvik-sdk/8.60.9/dalvik-sdk-8.60.9.zip && unzip dalvik-sdk-8.60.9.zip
  - sudo cp dalvik-sdk/rt/lib/ext/jfxrt.jar $JAVA_HOME/jre/lib/ext
  - sudo cp dalvik-sdk/rt/lib/jfxswt.jar $JAVA_HOME/jre/lib/
  - sudo cp dalvik-sdk/rt/lib/javafx.properties $JAVA_HOME/jre/lib
  - sudo cp dalvik-sdk/rt/lib/javafx.platform.properties $JAVA_HOME/jre/lib
  - sudo cp dalvik-sdk/lib/javafx-mx.jar $JAVA_HOME/lib
script:
  - mvn -q clean install -Pno-network
  - jdk_switcher use openjdk7
  - cd core
  - mvn -q clean package -Pno-network

after_success:
  - cd ../core
  - mvn jacoco:report coveralls:report

notifications:
  irc:
    channels: "irc.freenode.net#bitcoinj"
    skip_join: true
